services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /etc/nginx/:/etc/nginx/

  #cart
  cart_green:
    build:
      context: ./cart
    image: cart
    container_name: cart_green
    ports:
      - 8080:8080
    volumes:
      - ./cart:/root/cart
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  cart_blue:
    build:
      context: ./cart
    container_name: cart_blue
    ports:
      - 8087:8087
    volumes:
      - ./cart:/root/cart
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #coupon
  coupon_green:
    build:
      context: ./coupon
    container_name: coupon_green
    ports:
      - 8081:8081
    volumes:
      - ./coupon:/root/coupon
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  coupon_blue:
    build:
      context: ./coupon
    container_name: coupon_blue
    ports:
      - 8088:8088
    volumes:
      - ./coupon:/root/coupon
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #item
  item_green:
    build:
      context: ./item
    container_name: item_green
    ports:
      - 8082:8082
    volumes:
      - ./item:/root/item
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  item_blue:
    build:
      context: ./item
    container_name: item_blue
    ports:
      - 8089:8089
    volumes:
      - ./item:/root/item
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #order
  order_green:
    build:
      context: ./order
    container_name: order_green
    ports:
      - 8083:8083
    volumes:
      - ./order:/root/order
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  order_blue:
    build:
      context: ./order
    container_name: order_blue
    ports:
      - 8090:8090
    volumes:
      - ./order:/root/order
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #review
  review_green:
    build:
      context: ./review
    container_name: review_green
    ports:
      - 8084:8084
    volumes:
      - ./review:/root/review
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  review_blue:
    build:
      context: ./review
    container_name: review_blue
    ports:
      - 8091:8091
    volumes:
      - ./review:/root/review
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #user
  user_green:
    build:
      context: ./user
    container_name: user_green
    ports:
      - 8085:8085
    volumes:
      - ./user:/root/user
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  user_blue:
    build:
      context: ./user
    container_name: user_blue
    ports:
      - 8092:8092
    volumes:
      - ./user:/root/user
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  #image
  image_green:
    build:
      context: ./image
    container_name: image_green
    ports:
      - 8086:8086
    volumes:
      - ./image:/root/image
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=green

  image_blue:
    build:
      context: ./image
    container_name: image_blue
    ports:
      - 8093:8093
    volumes:
      - ./image:/root/image
    depends_on:
      - eureka-green
    environment:
      - SPRING_PROFILES_ACTIVE=blue

  eureka-green:
    build:
      context: ./eureka
    container_name: eureka-green
    ports:
      - 8761:8761
    volumes:
      - ./eureka:/root/eureka
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=local

  gateway-green:
    build:
      context: ./gateway
    container_name: gateway-green
    ports:
      - 8000:8000
    volumes:
      - ./eureka:/root/eureka
    depends_on:
      - eureka-green