spring:
  profiles:
    group:
      blue: "blue"
---
spring:
  data:
    redis:
      host: host.docker.internal
      port: 6379

  config:
    activate:
      on-profile: "blue"

jwt:
  secret:
    key: