spring:
  profiles:
    group:
      green: "green"
---
spring:
  data:
    redis:
      host: 13.125.10.163
      port: 6379

  config:
    activate:
      on-profile: "green"

jwt:
  secret:
    key: