server:
  port: 8081

spring:
  application:
    name: module-coupon-service
#  jpa:
#    hibernate:
#      ddl-auto: validate

#  profiles:
#    active: local

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/
