spring:
  profiles:
    group:
      "green": "green_port"
---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: "green_port"

  application:
    name: module-coupon-service

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://3.38.103.4:8761/eureka/

---

#spring:
#  profiles:
#    group:
#      "blue": "blue_port"
#---
#server:
#  port: 8088
#
#spring:
#  config:
#    activate:
#      on-profile: "blue_port"
#
#  application:
#    name: module-coupon-service
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#
#    service-url:
#      defaultZone: http://3.38.103.4:8761/eureka/