server:
  port: 8080

spring:
  application:
    name: module-cart-service

  jpa:
    hibernate:
      ddl-auto: validate

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.10.163:3306/fashion_mall?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: test
    password: 1q2w3e4r!@

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-green:8761/eureka/