spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/shopDB
    username: sa
    password: sa
