FROM openjdk:17-jdk
WORKDIR /app
ARG COMMON_JAR_FILE=../module-common/build/libs/module-common-0.0.1-SNAPSHOT-plain.jar
COPY ${COMMON_JAR_FILE} /app/common.jar
ARG COUPON_JAR_FILE=../module-coupon-service/build/libs/module-coupon-service-0.0.1-SNAPSHOT.jar
COPY ${COUPON_JAR_FILE} /app/coupon.jar
# Copy the application files for common and coupon profiles
COPY ../module-common/src/main/resources/application.yml /app/application-common.yml
COPY ../module-coupon-service/src/main/resources/application.yml /app/application-coupon.yml
ENTRYPOINT ["sh", "-c", "java -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.config.location=file:/app/ /app/coupon.jar"]
#jwt 오류 나기 전까지 된것. yml이랑 yml 설정해서 사용


## build 문제인가 해서 해봤는데 이 버전은 실패
#FROM gradle:7.5-jdk17 AS build
#
## Gradle 빌드 파일을 복사
#COPY . /app
#WORKDIR /app
#
## Gradle 빌드 실행
#RUN gradle build -x test # 이 부분이 빌드가 안되서 오류가 난다.
#
## 새로운 이미지에서 실제 실행
#FROM openjdk:17-jdk
#WORKDIR /app
#
## Gradle 빌드에서 생성된 .jar 파일을 복사
#COPY --from=build /app/module-common/build/libs/module-common-0.0.1-SNAPSHOT-plain.jar /app/common.jar
#COPY --from=build /app/module-coupon-service/build/libs/module-coupon-service-0.0.1-SNAPSHOT.jar /app/coupon.jar
#
## application.yml 파일을 복사
#COPY ../module-common/src/main/resources/application.yml /app/application-common.yml
#COPY ../module-coupon-service/src/main/resources/application.yml /app/application-coupon.yml
#
## 애플리케이션 실행
#ENTRYPOINT ["sh", "-c", "java -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -Dspring.config.location=file:/app/ /app/coupon.jar"]
