FROM openjdk:17-jdk
WORKDIR /app
ARG JAR_FILE=../module-gateway-service/build/libs/module-gateway-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8000
ENTRYPOINT ["java", "-jar", "app.jar"]