spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    s3:
      bucket: s3-bucket-shopdb