server:
  port: 8086

spring:
  application:
    name: module-image-service
  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-green:8761/eureka/

cloud:
  aws:
    credentials:
      accessKey: ${AWS_IAM_ACCESSKEY}
      secretKey: ${AWS_IAM_SECRET_ACCESSKEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: s3-bucket-shopdb