version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/demo/module-eureka-server/zip/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/demo/module-eureka-server/zip/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: root
