version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/demo/eureka/zip/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/demo/eureka/zip/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 300
      runas: root