spring:
  profiles:
    group:
      green: "green"
---
server:
  port: 8084

spring:
  config:
    activate:
      on-profile: "green"

  application:
    name: module-review-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.244.137:3306/fashion_mall?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: test
    password: 1q2w3e4r!@

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://43.203.244.137:8761/eureka/