server:
  port: 8083

spring:
  application:
    name: module-order-service
  jpa:
    hibernate:
      ddl-auto: validate

  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/

portOne:
  api:
    key: 5482317358863162
    secret: pu6XCV2hmrXm1Wt5SK5E8AE5TVuZjspOzkVLvuVFNBQcLmFJdscdfe0lrTISeAg3M1mwXftJhiwCuR71