spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  portOne:
    api:
      key: 5482317358863162
      secret: pu6XCV2hmrXm1Wt5SK5E8AE5TVuZjspOzkVLvuVFNBQcLmFJdscdfe0lrTISeAg3M1mwXftJhiwCuR71
