spring:
  profiles:
    group:
      "green": "green_port"
---
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: "green_port"

  application:
    name: module-order-service

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://3.38.103.4:8761/eureka/

portOne:
  api:
    key: ${PORTONE_API_KEY}
    secret: ${PORTONE_API_SECRET}

---

spring:
  profiles:
    group:
      "blue": "blue_port"
---
server:
  port: 8090

spring:
  config:
    activate:
      on-profile: "blue_port"

  application:
    name: module-order-service

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://3.38.103.4:8761/eureka/

portOne:
  api:
    key: ${PORTONE_API_KEY}
    secret: ${PORTONE_API_SECRET}