server:
  port: 8083

spring:
  application:
    name: module-order-service
  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-green:8761/eureka/

portOne:
  api:
    key:
    secret: