spring:
  profiles:
    group:
      "blue": "blue_port"
---
server:
  port: 8000

spring:
  config:
    activate:
      on-profile: "blue_port"
  application:
    name: module-gateway-service
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/