spring:
  profiles:
    group:
      blue: "blue"
---
server:
  port: 8000

spring:
  config:
    activate:
      on-profile: "blue"
  application:
    name: module-gateway-service
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://3.38.103.4:8761/eureka/