name: Cart Service CI/CD Pipeline

on:
  push:
    branches:
      - feature/cart  # feature/cart 브랜치에서만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Cache Maven and Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle
          key: ${{ runner.os }}-maven-gradle-${{ hashFiles('**/*.gradle*', '**/*.pom') }}
          restore-keys: |
            ${{ runner.os }}-maven-gradle-

      - name: Build project with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Prepare deployment package
        run: |
          mkdir -p before-deploy
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp Dockerfile before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r before-deploy.zip *
          mv before-deploy/before-deploy.zip deploy/SpringBoot_CI-CD.zip

      - name: Upload to S3
        run: |
          aws s3 cp deploy/SpringBoot_CI-CD.zip s3://aws-gyun-s3/SpringBoot_CI-CD.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name CartService \
            --deployment-group-name CartService_Group \
            --revision "revisionType=S3,s3Location={bucketName=aws-gyun-s3,bundleType=zip,key=SpringBoot_CI-CD.zip}" \
            --region ap-northeast-2
